# Generated by Django 4.2 on 2023-05-24 07:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0003_approvalreason"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ApprovalReason",
            new_name="Reason",
        ),
        migrations.AlterField(
            model_name="student",
            name="status",
            field=models.CharField(
                choices=[
                    ("received", "Received"),
                    ("approved", "Approved"),
                    ("disapproved", "Disapproved"),
                ],
                max_length=100,
            ),
        ),
    ]
